### PR TITLE
Provide FormValues for createDecorator

### LINKED ISSUE #38: Provide FormValues for createDecorator
If FormValues type in typescript is specified for a Form, then type 'Decorator<object>' is not assignable to type 'Decorator<FormValues>'

### PR DESCRIPTION
**Pull request by A11oW**
Fixes #38

### CODE REVIEW

**Comment by afzalsayed96** [comment]
Came here for this. Hope it gets merged.

**Comment by marjorg** [comment]
Really need this in one of my projects as well. @erikras any chance of this getting approved and released?

**Comment by erikras** [comment]
Published in [`v1.3.2`](https://github.com/final-form/final-form-calculate/releases/tag/v1.3.2).

**Comment by afzalsayed96** [comment]
Hey @erikras, unfortunately it looks like the updated types are not published in `v1.3.2`.

https://unpkg.com/browse/final-form-calculate@1.3.2/dist/index.d.ts

**Comment by tokenvolt** [comment]
Confirm, the typings are missing in `v1.3.2`

**Pull request merged**
