### PR TITLE
Add support for RegExp in calculation field array definition

### PR DESCRIPTION
**Pull request by zimme**
I'll add tests when you've decided if you want this or not.

Here's an example of working code with this PR.
```
createDecorator({
  {
      field: [
        `data[${index}].salesValue`,
        `data[${index}].totalOtherCosts`,
        `data[${index}].totalInvoiceCost`,
        new RegExp(`^data\\[${index}\\]\\.orderMethods\\[\\d+\\]\\.totalCost$`), // This will now work
        new RegExp(
          `^data\\[${index}\\]\\.goodsProcessing\\[\\d+\\]\\.totalCost$`,
        ),
      ],
      updates: {
        [`data[${index}].grandTotal`]: (_ignored, values) => {
          ...
```

### CODE REVIEW

**Comment by zimme** [comment]
Yes but currently you can only specify `field` as RegExp or String or Array of String. This also allows Array of String or RegExp.

**Comment by erikras** [comment]
Sorry. Can you please add the tests in another PR?

**Comment by erikras** [comment]
Published in [`v1.3.0`](https://github.com/final-form/final-form-calculate/releases/tag/v1.3.0).

**Comment by zimme** [comment]
Awesome! I'll try and get to the tests if I get some me time during the holidays, but i dont count on it as i recently got a baby :baby:

**Pull request merged**
