### PR TITLE
Add previous values to updates function

### PR DESCRIPTION
**Pull request by dbertella**
Following up #23 I've added previous values to update function along with some tests and types.
Let me know what you guys think about it

### CODE REVIEW

**Comment by rockingskier** [comment]
Nice!  You might want to update the docs in README too.

**Comment by dbertella** [comment]
Ehy guys any update on this? I almost forgot this was there :-P

**Comment by ArnaudWeyts** [comment]
This would be great for my use case as well, can this ge merged?

**Comment by erikras** [comment]
Published in [`v1.3.0`](https://github.com/final-form/final-form-calculate/releases/tag/v1.3.0).

**Pull request merged**
